//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpFatura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fatura()
        {
            this.FaturaDetays = new HashSet<FaturaDetay>();
        }
    
        public int No { get; set; }
        public Nullable<int> CariNo { get; set; }
        public string FaturaNumarasi { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<decimal> Kdv { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Cari Cari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturaDetay> FaturaDetays { get; set; }
    }
}
